import { defineAction } from 'redux-define'

import { LOGIN_ACTIONS, LOGOUT_ACTIONS, PROFILE_ACTIONS, SHOW_WALLET_ACTIONS } from '../state'

const LOGIN_ACTION_TYPE = defineAction('LOGIN_ACTION_TYPE', LOGIN_ACTIONS)
const LOGOUT_ACTION_TYPE = defineAction('LOGOUT_ACTION_TYPE', LOGOUT_ACTIONS)
const PROFILE_ACTION_TYPE = defineAction('PROFILE_ACTION_TYPE', PROFILE_ACTIONS)
const SHOW_WALLET_ACTION_TYPE = defineAction('WALLET_ACTION_TYPE', SHOW_WALLET_ACTIONS)

const LOGIN = {
  LOGIN_ACTION_TYPE,
  LOGOUT_ACTION_TYPE,
  PROFILE_ACTION_TYPE,
  SHOW_WALLET_ACTION_TYPE
}

export default LOGIN
