import { defineAction } from 'redux-define'

import {
  PUBLISH_POST_ACTIONS,
  LIST_POST_ACTIONS,
  COMMENT_POST_ACTIONS,
  CLEAR_COMMENT_POST_STATUS_ACTIONS,
  LIST_POST_COMMENT_ACTIONS,
  LIKE_POST_ACTIONS,
  LIST_FOLLOWERS_ACTIONS,
  TASK_PUBLISH_ACTIONS,
  CLEAR_TASK_PUBLISH_STATUS_ACTIONS
} from '../state'

const PUBLISH_POST_ACTION_TYPE = defineAction('PUBLISH_POST_ACTION_TYPE', PUBLISH_POST_ACTIONS)
const LIST_POST_ACTION_TYPE = defineAction('LIST_POST_ACTION_TYPE', LIST_POST_ACTIONS)
const COMMENT_POST_ACTION_TYPE = defineAction('COMMENT_POST_ACTION_TYPE', COMMENT_POST_ACTIONS)
const CLEAR_COMMENT_POST_STATUS_ACTION_TYPE = defineAction('CLEAR_COMMENT_POST_STATUS_ACTION_TYPE', CLEAR_COMMENT_POST_STATUS_ACTIONS)
const LIST_POST_COMMENT_ACTION_TYPE = defineAction('LIST_POST_COMMENT_ACTION_TYPE', LIST_POST_COMMENT_ACTIONS)
const LIKE_POST_ACTION_TYPE = defineAction('LIKE_POST_ACTION_TYPE', LIKE_POST_ACTIONS)
const LIST_FOLLOWERS_ACTION_TYPE = defineAction('LIST_FOLLOWERS_ACTION_TYPE', LIST_FOLLOWERS_ACTIONS)
const TASK_PUBLISH_ACTION_TYPE = defineAction('TASK_PUBLISH_ACTION_TYPE', TASK_PUBLISH_ACTIONS)
const CLEAR_TASK_PUBLISH_STATUS_ACTION_TYPE = defineAction('CLEAR_TASK_PUBLISH_STATUS_ACTION_TYPE', CLEAR_TASK_PUBLISH_STATUS_ACTIONS)

const PUBLISH = {
  PUBLISH_POST_ACTION_TYPE,
  LIST_POST_ACTION_TYPE,
  COMMENT_POST_ACTION_TYPE,
  CLEAR_COMMENT_POST_STATUS_ACTION_TYPE,
  LIST_POST_COMMENT_ACTION_TYPE,
  LIKE_POST_ACTION_TYPE,
  LIST_FOLLOWERS_ACTION_TYPE,
  TASK_PUBLISH_ACTION_TYPE,
  CLEAR_TASK_PUBLISH_STATUS_ACTION_TYPE
}

export default PUBLISH
