const SUCCEED = 'SUCCEED'
const FAILED = 'FAILED'
const ERROR = 'ERROR'

export const LOGIN_ACTIONS = [SUCCEED, FAILED, ERROR]
export const LOGOUT_ACTIONS = [SUCCEED]
export const PUBLISH_POST_ACTIONS = [SUCCEED, FAILED, ERROR]
export const LIST_POST_ACTIONS = [SUCCEED, FAILED, ERROR]
export const COMMENT_POST_ACTIONS = [SUCCEED, FAILED, ERROR]
export const CLEAR_COMMENT_POST_STATUS_ACTIONS = [SUCCEED]
export const LIST_POST_COMMENT_ACTIONS = [SUCCEED, FAILED, ERROR]
export const LIKE_POST_ACTIONS = [SUCCEED, FAILED, ERROR]
export const LIST_FOLLOWERS_ACTIONS = [SUCCEED, FAILED, ERROR]
export const SHOW_PROFILE_ACTIONS = [SUCCEED, FAILED, ERROR]
export const PROFILE_ACTIONS = [SUCCEED, FAILED, ERROR]
export const SHOW_WALLET_ACTIONS = [SUCCEED, FAILED, ERROR]
export const TASK_PUBLISH_ACTIONS = [SUCCEED, FAILED, ERROR]
export const CLEAR_TASK_PUBLISH_STATUS_ACTIONS = [SUCCEED]
